services:
  backend:
    image: wiktoriakolodziej/publictransportnavigator-backend:v2
    container_name: backend
    ports:
      - "5000:8080" 
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:DefaultConnection=Host=postgres;Database=database;Username=postgres;Password=Lajdksauk3468298
      - ConnectionStrings:Default=Host=postgres;Database=database;Username=postgres;Password=Lajdksauk3468298
      - ConnectionStrings:Redis=redis:6379
      - Jwt:Key=SuperSecureRandomJwtKeyWithMin32Chars
      - PathFinderSettings:NumOfWorkers=5
      - PathFinderSettings:CheckIntervalMilliseconds=10
      - PathFinderSettings:TimeoutMilliseconds=1000
      - PathFinderSettings:PathFinderType=Dijkstra
      - BusData:Url=https://otwartedane.metropoliagzm.pl/dataset/rozklady-jazdy-i-lokalizacja-przystankow-gtfs-wersja-rozszerzona
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - postgres
      - redis

  frontend:
    image: wiktoriakolodziej/publictransportnavigator-frontend:v2
    container_name: frontend
    ports:
      - 80:80
    expose:
      - 80
    networks:
      - internalnet

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Lajdksauk3468298
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:

networks:
  internalnet:
    driver: bridge

